In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(3, 2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2, 3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 5, 3, 0, 1],
       [0, 1, 6, 6, 9],
       [0, 2, 3, 2, 5]])

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.8078869 , 0.64549032, 0.79731606],
       [0.74188048, 0.9438858 , 0.0970879 ],
       [0.1191728 , 0.85601746, 0.38429839],
       [0.99121821, 0.40052135, 0.71521621],
       [0.68464755, 0.73712895, 0.49884596]])

In [26]:
random_array_2.shape

(5, 3)

In [27]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.76111123, 0.59165252, 0.9111772 ],
       [0.28171636, 0.07235515, 0.43714323],
       [0.37310032, 0.24021058, 0.89475575],
       [0.08725778, 0.1688727 , 0.5501531 ],
       [0.24512205, 0.2837967 , 0.1797299 ]])

In [41]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [52]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [48]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.48582523, 0.13687612, 0.34353653],
       [0.32442617, 0.3004189 , 0.1655014 ],
       [0.41490177, 0.44812066, 0.77490038],
       [0.7963907 , 0.52239013, 0.4606303 ],
       [0.7782136 , 0.88728895, 0.67491877]])

In [33]:
random_array_4.shape

(5, 3)